const wordImages = {
  cam: require('../images/cam.jpg'),
  can: require('../images/can.jpg'),
  cap: require('../images/cap.jpg'),
  cat: require('../images/cat.jpg'),
  fan: require('../images/fan.jpg'),
  fat: require('../images/fat.jpg'),
  fin: require('../images/fin.jpg'),
  fit: require('../images/fit.jpg'),
  lap: require('../images/lap.jpg'),
  lit: require('../images/lit.jpg'),
  lip: require('../images/lip.jpg'),
  man: require('../images/man.jpg'),
  map: require('../images/map.jpg'),
  mat: require('../images/mat.jpg'),
  nap: require('../images/nap.jpg'),
  nil: require('../images/nil.jpg'),
  nip: require('../images/nip.jpg'),
  pal: require('../images/pal.jpg'),
  pan: require('../images/pan.jpg'),
  pat: require('../images/pat.jpg'),
  pin: require('../images/pin.jpg'),
  pip: require('../images/pip.jpg'),
  pit: require('../images/pit.jpg'),
  sap: require('../images/sap.jpg'),
  sat: require('../images/sat.jpg'),
  sim: require('../images/sim.jpg'),
  sin: require('../images/sin.jpg'),
  sip: require('../images/sip.jpg'),
  sit: require('../images/sit.jpg'),
  tan: require('../images/tan.jpg'),
  tap: require('../images/tap.jpg'),
  zap: require('../images/zap.jpg'),
  zip: require('../images/zip.jpg'),
  zit: require('../images/zit.jpg'),
  unknown: require('../images/unknown.jpg'),
}

export default wordImages;
