const wordSounds = {
  cam: require('../audio/cam.wav'),
  can: require('../audio/can.wav'),
  cap: require('../audio/cap.wav'),
  cat: require('../audio/cat.wav'),
  fan: require('../audio/fan.wav'),
  fat: require('../audio/fat.wav'),
  fin: require('../audio/fin.wav'),
  fit: require('../audio/fit.wav'),
  lap: require('../audio/lap.wav'),
  lip: require('../audio/lip.wav'),
  lit: require('../audio/lit.wav'),
  man: require('../audio/man.wav'),
  map: require('../audio/map.wav'),
  mat: require('../audio/mat.wav'),
  nap: require('../audio/nap.wav'),
  nil: require('../audio/nil.wav'),
  nip: require('../audio/nip.wav'),
  pal: require('../audio/pal.wav'),
  pam: require('../audio/pam.wav'),
  pan: require('../audio/pan.wav'),
  pat: require('../audio/pat.wav'),
  pin: require('../audio/pin.wav'),
  pip: require('../audio/pip.wav'),
  pit: require('../audio/pit.wav'),
  sap: require('../audio/sap.wav'),
  sat: require('../audio/sat.wav'),
  sim: require('../audio/sim.wav'),
  sin: require('../audio/sin.wav'),
  sip: require('../audio/sip.wav'),
  sit: require('../audio/sit.wav'),
  tan: require('../audio/tan.wav'),
  tap: require('../audio/tap.wav'),
  zap: require('../audio/zap.wav'),
  zip: require('../audio/zip.wav'),
  zit: require('../audio/zit.wav'),
  bubble_machine: require('../audio/bubble_machine.mp3'),
  machine_reverse: require('../audio/machine_reverse.mp3'),
}

export default wordSounds;
