const wordSounds = {
  cam: require('../android/app/src/main/res/raw/cam.wav'),
  can: require('../android/app/src/main/res/raw/can.wav'),
  cap: require('../android/app/src/main/res/raw/cap.wav'),
  cat: require('../android/app/src/main/res/raw/cat.wav'),
  fan: require('../android/app/src/main/res/raw/fan.wav'),
  fat: require('../android/app/src/main/res/raw/fat.wav'),
  fin: require('../android/app/src/main/res/raw/fin.wav'),
  fit: require('../android/app/src/main/res/raw/fit.wav'),
  lap: require('../android/app/src/main/res/raw/lap.wav'),
  lip: require('../android/app/src/main/res/raw/lip.wav'),
  lit: require('../android/app/src/main/res/raw/lit.wav'),
  man: require('../android/app/src/main/res/raw/man.wav'),
  map: require('../android/app/src/main/res/raw/map.wav'),
  mat: require('../android/app/src/main/res/raw/mat.wav'),
  nap: require('../android/app/src/main/res/raw/nap.wav'),
  nil: require('../android/app/src/main/res/raw/nil.wav'),
  nip: require('../android/app/src/main/res/raw/nip.wav'),
  pal: require('../android/app/src/main/res/raw/pal.wav'),
  pam: require('../android/app/src/main/res/raw/pam.wav'),
  pan: require('../android/app/src/main/res/raw/pan.wav'),
  pat: require('../android/app/src/main/res/raw/pat.wav'),
  pin: require('../android/app/src/main/res/raw/pin.wav'),
  pip: require('../android/app/src/main/res/raw/pip.wav'),
  pit: require('../android/app/src/main/res/raw/pit.wav'),
  sap: require('../android/app/src/main/res/raw/sap.wav'),
  sat: require('../android/app/src/main/res/raw/sat.wav'),
  sim: require('../android/app/src/main/res/raw/sim.wav'),
  sin: require('../android/app/src/main/res/raw/sin.wav'),
  sip: require('../android/app/src/main/res/raw/sip.wav'),
  sit: require('../android/app/src/main/res/raw/sit.wav'),
  tan: require('../android/app/src/main/res/raw/tan.wav'),
  tap: require('../android/app/src/main/res/raw/tap.wav'),
  zap: require('../android/app/src/main/res/raw/zap.wav'),
  zip: require('../android/app/src/main/res/raw/zip.wav'),
  zit: require('../android/app/src/main/res/raw/zit.wav'),
  bubble_machine: require('../android/app/src/main/res/raw/bubble_machine.mp3'),
  machine_reverse: require('../android/app/src/main/res/raw/machine_reverse.mp3'),
  welldone: require('../android/app/src/main/res/raw/welldone.wav'),
  boink: require('../android/app/src/main/res/raw/boink.wav'),
}

export default wordSounds;
